### ISSUE TITLE
trouble getting gsutil to cp files to GCS

### ISSUE THREAD

**Issue by iampatgrady** [GoogleCloudPlatform/cloud-for-marketing#14]
Having trouble getting gsutil to work with Tentacles naming convention. The gsutil is throwing an error

```
gsutil cp -r API[GS]_config[foo]_test.csv gs://example
CommandException: No URLs matched: API[GS]_config[foo]_test.csv
```

Reference:
https://github.com/GoogleCloudPlatform/gsutil/issues/290

**Comment by lushu** [comment]
Thanks for the feedback. I will look into it for an alternative symbol to mark it.

**Comment by lushu** [comment]
`{}` can be used as the marker of API and config in the file names as well. gsutil should support `{}`.
