### ISSUE TITLE
update nodejs 8 code base to 10

### ISSUE THREAD

**Issue by codatr0n** [GoogleCloudPlatform/cloud-for-marketing#15]
Just received a notification on one of my Google Cloud Projects, that nodejs 8 code base should be updated to 10, as v8 won't be supported as of march 15 2021.

I have successfully deployed an instance of the Tentacles project without actually knowing any nodejs - I'm a python guy :)

How do I update to v10? .. or could you update this project?

**Comment by lushu** [comment]
Yes. A new version for Tentacles is under working for and will be pushed to GitHub in one month. Nodejs10 is one of the updates.

**Comment by codatr0n** [comment]
Thanks... much appreciated :)
