### ISSUE TITLE
Campaign manager configuration - what does the quantity represent

### ISSUE THREAD

**Issue by droose-nayan** [GoogleCloudPlatform/cloud-for-marketing#22]
In the example [here](https://github.com/GoogleCloudPlatform/cloud-for-marketing/tree/master/marketing-analytics/activation/gmp-googleads-connector#43-cm-dcmdfa-reporting-and-trafficking-api-to-upload-offline-conversions), the quantity is set to 1, but it doesn't say what this quantity represents. Does this correspond to the amount of products per order? Or is this used to deduplicate the orders by order ID (ordinal)?

**Comment by lushu** [comment]
For the details of QPS of Campaign manager, please see: 
https://developers.google.com/doubleclick-advertisers/quotas#quota_limits
