### ISSUE TITLE
Unable to Install on GCP - Step 14 - nodejs-common package issue

### ISSUE THREAD

**Issue by emilija1988** [GoogleCloudPlatform/cloud-for-marketing#23]
Unable to install on GCP. Package error.  (nodejs-common) that is not longer available via npm registry. 
Error when deploying cloud functions: Step 14
Error code [404](url)
![image](https://user-images.githubusercontent.com/47056447/108764030-5e03af80-7552-11eb-9e8c-4870476cc79d.png)

**Comment by lushu** [comment]
It should be fixed. Please pull the code and try again. Thank you.
