### ISSUE TITLE
Why Google Cloud Dataflow or Apache Beam

### ISSUE THREAD

**Issue by Joshuacourse** [GoogleCloudPlatform/cloud-for-marketing#29]
I love the idea of Future Customer Value Segments. However, from an implementation perspective, Dataflow or Apache Beam looks like overkill as a batch prediction solution. Are there reasons why a customized python solution (e.g Sklearn) or BigQuery ML not a better solution?

**Comment by mohabfekry** [comment]
Hi Joshua,

Thanks a lot for your input. The reason primarily lies around the modelling framework used by FoCVS (probabilistic modelling through the python 'lifetimes' package), which requires fewer inputs / fewer training epochs than what Sklearn or BQML would need. Dataflow / Beam is just a wrapper around the framework to enable it to scale and utilise the power of Cloud Computing. Depending on your business operating model and what exactly you are trying to predict, ML could indeed be the more suitable option.

Thanks,
Mohab
