### ISSUE TITLE
Unrecognized arguments during deployment of Cloud Function 3

### ISSUE THREAD

**Issue by flowstack** [GoogleCloudPlatform/cloud-for-marketing#3]
Sometimes the input script fails when it tries to create cloud function 3. Seems to indicate there's a blank argument.

For additional information I am only setting up Measurement Protocol and using Europe West 2. I've created a MP and Data Import setup previously and it has worked fine.

<img width="568" alt="Screenshot 2019-09-07 at 13 54 25" src="https://user-images.githubusercontent.com/2894755/64475185-27c44b80-d177-11e9-95cc-9168f35f7c5b.png">

**Comment by lushu** [comment]
Thank you @flowstack for submitting this issue. It has been [fixed](https://github.com/GoogleCloudPlatform/cloud-for-marketing/commit/fa71fd56b8089f37e2c99a57dd309099991d06bb). Please update the code and try again.
