### ISSUE TITLE
Requests to CM API version 3.3 will no longer work

### ISSUE THREAD

**Issue by AlmasToimbekov** [GoogleCloudPlatform/cloud-for-marketing#30]
[This](https://github.com/GoogleCloudPlatform/cloud-for-marketing/blob/d83054d81f084c5a47f9d725840c0ad765cf88e8/marketing-analytics/activation/common-libs/nodejs-common/src/apis/dfa_reporting.js#L36) line, I believe, causes 

> "Requests to version 3.3 will no longer work..." 

warning message from CM360 (see the screenshot attached). Looks like we have 30 days for fixing this.
<img width="647" alt="Screen Shot 2021-05-30 at 22 11 52" src="https://user-images.githubusercontent.com/47621543/120111556-3006ba80-c194-11eb-8574-3524f38f661b.png">

**Comment by lushu** [comment]
Thank you for addressing this issue. You are right, a new version will be released soon to solve it.

**Comment by lushu** [comment]
Fixed with this [commit](https://github.com/GoogleCloudPlatform/cloud-for-marketing/commit/42da68900f20de92f30010c7935b194082b53ed5)
