### ISSUE TITLE
Region Names in Step 5 of the Installation Process

### ISSUE THREAD

**Issue by LukaData** [GoogleCloudPlatform/cloud-for-marketing#35]
Step 5 of the installation process currently seems to have a bug that uses the value "NAME:" for every odd option in the list (see the screenshot below). Valid (even) options work as expected.

![image](https://user-images.githubusercontent.com/10385111/142942648-637ff1c4-f865-4c26-92f3-e3ce78a504b1.png)

**Comment by lushu** [comment]
Thanks @LukaData We knew this bug and it would be fixed in next version.

**Comment by lushu** [comment]
Fixed in Tentacles v2
