### ISSUE TITLE
Can tentacles_init cloud function be delayed?

### ISSUE THREAD

**Issue by flowstack** [GoogleCloudPlatform/cloud-for-marketing#4]
My input file to the 'outbound' Cloud Storage bucket is being generated by Dataprep/Dataflow. What I find happening is that the cloud function is too eager. Dataflow/Dataprep starts to write the output file, and the cloud function executes before the file has been completely written, resulting in invalid or partial data being sent to GA.

Would it be possible to add a mechanism to delay the cloud function execution? Maybe a parameter in the filename to tell the init function to pause for X seconds once a new file is detected, or even a way to change the overall functionality of the Cloud Function Cloud Storage trigger.

**Comment by lushu** [comment]
The tentacles_init cloud function is triggered on 'google.storage.object.finalize'. So ideally it would run only after the file is finished. 

Currently I don't have a process involved Dataprep or Dataflow. Can you do some tests, e.g. use a CF to catch the event of those files from Dataprep/Dataflow and what happened?

**Comment by lushu** [comment]
Close this due to inactivity.
