### ISSUE TITLE
Issue deploying config to Cloud Datastore

### ISSUE THREAD

**Issue by flowstack** [GoogleCloudPlatform/cloud-for-marketing#5]
A client has already set up Datastore rather than Firestore in their project (for something unrelated to Tentacles). Although the database is empty, it can't be upgraded because, according to the message shown, 'data has been created and deleted'.

When running the './deploy.sh update_api_config' Tentacles command, the following message appears:

'In detecting Firestore mode: 9 FAILED_PRECONDITION: The Cloud Firestore API is not available for Cloud Datastore projects.' (see screenshot for more).

Is there a way around this? What should the process be? Can Tentacles use Cloud Datastore, and can the config be created manually?

![tentacles](https://user-images.githubusercontent.com/2894755/68321788-3d43ec00-00ba-11ea-891e-a0811ae568f3.png)
Many thanks

**Comment by lushu** [comment]
Hi,

The message is expected in an environment of Datastore. (The code will try to determine the background database type by trying some Firestore code. It will turn to use Datastore if it got this error).

From the log, it looks like it had uploaded the configuration successfully. Please check the Datastore see if it's there. Thank you.

Cheers,
Shu

**Comment by flowstack** [comment]
Thanks Shu. You are correct of course. Took Datastore a few minutes to show the config settings in there.
